name: Jest
on:
  pull_request:
    branches:
      - master
jobs:
  name: build and test
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run jest tests
      run: yarn polkadot:test