name: CREDENTIALS TEST
on:
  pull_request:
    branches:
      - master

jobs:
  credentials-test:
    runs-on: ubuntu-latest
    steps:
      - uses: jamessingleton/is-organization-member@v1.0.1
        id: checkUserMember
        with:
          organization: w3f
          username: ${{ github.actor }}
          token: ${{ secrets.ACCESS_KEY }}
      - if: steps.is_organization_member.outputs.result == true
        run: echo User belongs to w3f org
